//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins_passwords
    {
        public int id_login { get; set; }
        public Nullable<int> id_user { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual User User { get; set; }
    }
}
