//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public string date { get; set; }
        public string status { get; set; }
        public string decription { get; set; }
        public string price { get; set; }
        public int id_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
